### ISSUE TITLE
download data problem 

### ISSUE THREAD

**Issue by QiaolinLu** [microsoft/foldingdiff#7]
Hello, when I download data with the script _download_alphafold.sh_,  files are 404 NOT FOUND
and the script download_cath.sh, md5sum: cath/cath-dataset-nonredundant-S40.pdb.tgz: no properly formatted MD5 checksum lines found
Coud you please fix it? Thanks.

**Comment by wukevin** [comment]
The issue with the CATH download script has been fixed in https://github.com/microsoft/foldingdiff/commit/658de68a49979cb21a627ab3bb440f467a824661 - the error did not affect actual file download.

We do not support alphafold dataset or its download at this time. The script is simply there as a leftover file from initial development.
